// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.EfCore;

#nullable disable

namespace TaxCalculator.EfCore.Migrations
{
    [DbContext(typeof(TaxCalculatorContext))]
    [Migration("20220807190806_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TaxCalculator.Models.Data.TaxBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IsoCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PercentRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RangeLowerBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RangeUpperBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsoCountryCode", "TaxYear");

                    b.ToTable("TaxBands");
                });

            modelBuilder.Entity("TaxCalculator.Models.Data.TaxYear", b =>
                {
                    b.Property<string>("IsoCountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IsoCountryCode", "Year");

                    b.ToTable("TaxYears");
                });

            modelBuilder.Entity("TaxCalculator.Models.Data.TaxBand", b =>
                {
                    b.HasOne("TaxCalculator.Models.Data.TaxYear", null)
                        .WithMany("TaxBands")
                        .HasForeignKey("IsoCountryCode", "TaxYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxCalculator.Models.Data.TaxYear", b =>
                {
                    b.Navigation("TaxBands");
                });
#pragma warning restore 612, 618
        }
    }
}
